steps:
  # testing if the build is working
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "compute",
        "ssh",
        "--zone",
        "us-west1-a",
        "ray@instance",
        "--command",
        "screen -X -S treevia quit; cd ~/treevia; git pull; npm ci; npm run build; screen -d -m -S treevia sudo ts-node index.ts",
      ]
options:
  logging: CLOUD_LOGGING_ONLY
